/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __KERNEL_RTPM_PRIO__
#define __KERNEL_RTPM_PRIO__

#define CONFIG_MT_RT_MONITOR
#ifdef CONFIG_MT_RT_MONITOR
#define MT_ALLOW_RT_PRIO_BIT 0x10000000
#else
#define MT_ALLOW_RT_PRIO_BIT 0x0
#endif

#define REG_RT_PRIO(x) ((x) | MT_ALLOW_RT_PRIO_BIT)

////////////////////////////////////////////////////////////////////////
//DEFINE MM GROUP PRIORITY
#define RTPM_PRIO_MM_GROUP_BASE			(10)
#define RTPM_PRIO_MM_GROUP_A			(RTPM_PRIO_MM_GROUP_BASE+0)
#define RTPM_PRIO_MM_GROUP_B			(RTPM_PRIO_MM_GROUP_BASE+10)
#define RTPM_PRIO_MM_GROUP_C			(RTPM_PRIO_MM_GROUP_BASE+20)
#define RTPM_PRIO_MM_GROUP_D			(RTPM_PRIO_MM_GROUP_BASE+30)
#define RTPM_PRIO_MM_GROUP_E			(RTPM_PRIO_MM_GROUP_BASE+40)
#define RTPM_PRIO_MM_GROUP_F			(RTPM_PRIO_MM_GROUP_BASE+50)
#define RTPM_PRIO_MM_GROUP_G			(RTPM_PRIO_MM_GROUP_BASE+60)
#define RTPM_PRIO_MM_GROUP_H			(RTPM_PRIO_MM_GROUP_BASE+70)
#define RTPM_PRIO_MM_GROUP_I			(RTPM_PRIO_MM_GROUP_BASE+80)

////////////////////////////////////////////////////////////////////////
// DEFIN MTK RT PRIORITY 

#define RTPM_PRIO_SWLOCKUP                  REG_RT_PRIO(99)
#define RTPM_PRIO_AED                       REG_RT_PRIO(99)
#define RTPM_PRIO_WDT                       REG_RT_PRIO(1)

#define RTPM_PRIO_TPD                       REG_RT_PRIO(4)
#define RTPM_PRIO_KSDIOIRQ                  REG_RT_PRIO(1)

#define RTPM_PRIO_AUDIO_PLAYBACK            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+5)
#define RTPM_PRIO_VIDEO_PLAYBACK_THREAD     REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+5) //TimeEventQueue
#define RTPM_PRIO_SCRN_UPDATE               REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+4)
#define RTPM_PRIO_AUDIO_COMMAND             REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+2)
#define RTPM_PRIO_AUDIO_CCCI_THREAD         REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+2)

#define RTPM_PRIO_CAMERA_PREVIEW            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+1)
#define RTPM_PRIO_CAMERA_COMPRESS           REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+0)

#define RTPM_PRIO_MATV_AUDIOPLAYER          REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+0)
#define RTPM_PRIO_FM_AUDIOPLAYER            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+0)
#define RTPM_PRIO_AUDIO_I2S                 REG_RT_PRIO(RTPM_PRIO_MM_GROUP_I+0)

#define RTPM_PRIO_CAMERA_DISPLAY            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_H+9)
#define RTPM_PRIO_CAMERA_SHUTTER            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_H+9)
#define RTPM_PRIO_CAMERA_RECORD             REG_RT_PRIO(RTPM_PRIO_MM_GROUP_H+9)
#define RTPM_PRIO_FB_THREAD                 REG_RT_PRIO(RTPM_PRIO_MM_GROUP_H+7)
#define RTPM_PRIO_SURFACEFLINGER            REG_RT_PRIO(RTPM_PRIO_MM_GROUP_H+4)

#define RTPM_PRIO_VIDEO_YUV_BUFFER          REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+8)
#define RTPM_PRIO_AUDIO_RECORD              REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+7)
#define RTPM_PRIO_OMX_AUDIO                 REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+6)
#define RTPM_PRIO_OMX_CMD_AUDIO             REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+6)
#define RTPM_PRIO_OMX_VIDEO_ENCODE          REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+5)
#define RTPM_PRIO_OMX_VIDEO                 REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+5)
#define RTPM_PRIO_OMX_VIDEO_DECODE          REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+4)

#define RTPM_PRIO_VIDEO_BS_BUFFER           REG_RT_PRIO(RTPM_PRIO_MM_GROUP_G+3)
#define RTPM_PRIO_MIDI_FILE                 REG_RT_PRIO(RTPM_PRIO_MM_GROUP_C+0)

#define RTPM_PRIO_AUDIOTRACK_THREAD         REG_RT_PRIO(1)
// Total 
#define RTPM_PRIO_NUM	30
////////////////////////////////////////////////////////////////////////////////
//Removed
//#define RTPM_PRIO_FB_THREAD                 REG_RT_PRIO(87)
//#define RTPM_PRIO_SURFACE_OUT               REG_RT_PRIO(80)

#endif
