/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#include <config.h>

/*Common Registers*/
#define USB2D0_INTRIN_16   (CONFIG_SYS_USB_DEVICE | 0x100)
#define USB2D0_POWER_8     (CONFIG_SYS_USB_DEVICE | 0x102)
#define USB2D0_FADDR_8     (CONFIG_SYS_USB_DEVICE | 0x103)
#define USB2D0_INTRINE_16  (CONFIG_SYS_USB_DEVICE | 0x104)
#define USB2D0_INTROUT_16  (CONFIG_SYS_USB_DEVICE | 0x106)
#define USB2D0_INTRUSBE_8  (CONFIG_SYS_USB_DEVICE | 0x108)
#define USB2D0_INTRUSB_8   (CONFIG_SYS_USB_DEVICE | 0x109)
#define USB2D0_INTROUTE_16 (CONFIG_SYS_USB_DEVICE | 0x10a)
#define USB2D0_TSTMODE_8   (CONFIG_SYS_USB_DEVICE | 0x10c)
#define USB2D0_INDEX_8     (CONFIG_SYS_USB_DEVICE | 0x10d)
#define USB2D0_FRAME_16    (CONFIG_SYS_USB_DEVICE | 0x10e)

/*Indexed Registers*/
#define USB2D0_INCSR0_8    (CONFIG_SYS_USB_DEVICE | 0x110)
#define USB2D0_INCSR_16    (CONFIG_SYS_USB_DEVICE | 0x110)
#define USB2D0_INMAXP_16   (CONFIG_SYS_USB_DEVICE | 0x112)
#define USB2D0_OUTCSR_16   (CONFIG_SYS_USB_DEVICE | 0x114)
#define USB2D0_OUTMAXP_16  (CONFIG_SYS_USB_DEVICE | 0x116)
#define USB2D0_OUTCOUNT0_8 (CONFIG_SYS_USB_DEVICE | 0x11a)
#define USB2D0_OUTCOUNT_16 (CONFIG_SYS_USB_DEVICE | 0x11a)

/*FIFOs*/
#define USB2D0_FIFO_0 (CONFIG_SYS_USB_DEVICE | 0x120)
#define USB2D0_FIFO_1 (CONFIG_SYS_USB_DEVICE | 0x124)
#define USB2D0_FIFO_2 (CONFIG_SYS_USB_DEVICE | 0x128)
#define USB2D0_FIFO_3 (CONFIG_SYS_USB_DEVICE | 0x12c)

void usb_dev_init(void);
